<a href="https://colab.research.google.com/github/ackerfeld/ackerdfeld/blob/main/EC_Tarea_1_Estad%C3%ADstica_Computacional_Cristian_Alca%C3%ADno-Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 1 - Estadística Computacional

- Nombre: Cristian Alcaíno Fernández

Curso: Estadística Computacional

Doctorado en Estadística


Responda las preguntas que se indican colocando el código requerido. El Notebook se entrega totalmente ejecutado.

**Ingrese los Toolbox que se utilizarán en este Jupyter**

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import spearmanr

## 1. Indicadores estadísticos.

En estadística, en muchas ocasiones se requiere implementar indicadores o estadísticos. En esta pregunta deberá implementar los siguientes indicadores:

1. **Symmetric mean absolute percentage error (SMAPE or sMAPE)**: es una medida de precisión basada en errores porcentuales (o relativos).

$$sMAPE = \frac{100\%}{n}\sum_{t=1}^n \frac{|F_t-A_t|}{(|A_t|+|F_t|)/2}$$

donde $A_t$ es el valor real y $F_t$ es el valor de pronóstico.

Implementar la Función sMAPE:

Aplicar la función sMAPE de las siguientes listas:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }
       
Predicción = { 3.58,  4.3 ,  0.5 , -3.11, -1.94,  3.71,  1.56, -1.55, -2.77,
       -0.51,  2.93,  2.14, -1.76, -1.96, -0.51,  2.96, -0.34, -3.33,
       -3.49,  1.5}


**Función para sMAPE encapsulado**

In [ ]:
def smape(real,prons):
  real=np.array(real)  #convierte el conjunto de datos en un arreglo numpy
  prons=np.array(prons) #convierte el conjunto de datos en un arreglo numpy
  return (1/len(real)) * np.sum(2 * np.abs(prons - real) / (np.abs(real) + np.abs(prons))) #calcula y retorna el valor sMAPE


 **Calculamos SMAPE**

In [ ]:
#Ingreso de los datos
Dato = [ 1.5 , 2.89, -0.08, -2.93, -1.35, 2.26, 2.47, -1.05, -2.98, -0.41, 2.78, 1.78, -1.91, -2.71, 0.58, 3. , 0.9 , -2.56, -2.15, 1.5 ]
Pronostico = [3.58, 4.3 , 0.5 , -3.11, -1.94, 3.71, 1.56, -1.55, -2.77, -0.51, 2.93, 2.14, -1.76, -1.96, -0.51, 2.96, -0.34, -3.33, -3.49, 1.5]


**Impriendo sMAPE**

In [ ]:
# LLama a la función sMAPE
result = smape(Dato, Pronostico)
# Imprime el resultado sMAPE
print("SMAPE :",result)

SMAPE : 0.5315507816129963


2. **Coeficiente de correlación de Spearman ($\rho$)**: es una medida de la correlación (la asociación o interdependencia) entre dos variables aleatorias (tanto continuas como discretas). Para calcular $\rho$, los datos son ordenados y reemplazados por su respectivo orden.

El estadístico está dado por:

$$\rho = 1 - \frac{6\sum_i D_{(i)}^2}{N(N^2-1)}$$

donde $D_{(i)}$ es la diferencia entre los correspondientes estadísticos de orden de $x$ e $y$. $N$ es el número de parejas de datos.


Calcular el coeficiente de correlación de Spearman para los siguientes datos:
    
Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }
       
Predicción = { 3.58,  4.3 ,  0.5 , -3.11, -1.94,  3.71,  1.56, -1.55, -2.77,
       -0.51,  2.93,  2.14, -1.76, -1.96, -0.51,  2.96, -0.34, -3.33,
       -3.49,  1.5}

**Función coeficiente de Spearman encapsulado en una función**

In [ ]:
def coefSpearman(dato, pron):
  matriz={} #Crea una un conjunto vació
  matriz['Datos']=(dato) #crea una clave con los datos de la lista datos
  matriz['Prediccion']=(pron) #crea una clave con los datos de la lista predicción
  df=pd.DataFrame(matriz) #usa pandas para crear un DataFrame con los de la lista Dato y Predicción
  df['D_i']=df['Datos']-df['Prediccion'] #calcula el valor D_i y agrega una columna al DataFrame
  df['D_i^2']=df['D_i']*df['D_i']  #Calcula el valor D_i al cuadrado y agrega una coluna al DataFrame
  n=df.shape[0] #cuenta el número de filas de la matriz del DataFrame
  D_i_cuadrado=df['D_i^2'].sum() #suma todos los valores de la columnna D_i al cuadrado, valor usado en la fórmula
  return (1-(6*D_i_cuadrado)/(n*(n**2-1))) #calcula y retorna el valor del coeficiente de Spearman

**Datos**

In [ ]:
dato = [ 1.5 , 2.89, -0.08, -2.93, -1.35, 2.26, 2.47, -1.05, -2.98, -0.41, 2.78, 1.78, -1.91, -2.71, 0.58, 3. , 0.9 , -2.56, -2.15, 1.5 ]
pron = [ 3.58, 4.3 , 0.5 , -3.11, -1.94, 3.71, 1.56, -1.55, -2.77, -0.51, 2.93, 2.14, -1.76, -1.96, -0.51, 2.96, -0.34, -3.33, -3.49, 1.5]





**LLamando a la función e imprimiendo el coeficiente**

In [ ]:
coef_spear=coefSpearman(dato,pron)
print('\nEl coeficiente de spearman es: %f' %coef_spear)


El coeficiente de spearman es: 0.987880


3. **Coeficiente de Gini:** es una medida de la desigualdad. El coeficiente de Gini es un número entre 0 y 1, en donde 0 se corresponde con la perfecta igualdad (todos tienen los mismos ingresos) y donde el valor 1 se corresponde con la perfecta desigualdad. Para obtener el coeficiente de Gini, en general se utiliza la fórmila de Brown:

$$G = \left|1 - \sum_{k=1}^n (X_{k+1}-X_k)(Y_{k+1}+Y_k)\right|$$

donde $X$ e $Y$ corresponden a la proporción acumulada de las variables.

Implementar la función que calcule el coeficiente de Gini.


Obtener el coeficiente de Gini para las siguientes dos proporciones:

| Variables Acumuladas| Clase 1 | Clase 2 | Clase 3 | Clase 4 | Clase 5 |
| --- | --- | --- | --- | --- | --- |
| X | 0.09 | 0.33 | 0.45 | 0.78 | 1 |
| Y | 0.17 | 0.48 | 0.62 | 0.86 | 1 |



**Definición de la función**

In [ ]:
#definición de la función
def coefGini(Var_X ,Var_Y ):
  Matriz_datos={}#Crea un conjunto vació
  Matriz_datos['VarX']=Var_X #se agrega la clave y datos al diccionario
  Matriz_datos['VarY']=Var_Y #se agrega la clave y datos al diccionario
  df_1=pd.DataFrame(Matriz_datos, index=['Clase 1','Clase 2','Clase 3','Clase 4','Clase 5']) #se crea el dataFrame con pandas
  df_1['X_k+1-X_k']=(df_1['VarX'].shift(-1)-df_1['VarX']).shift(1) #Se calcula la diferencia de los datos X
  df_1['Y_k+1+Y_k']=(df_1['VarY'].shift(-1)+df_1['VarY']).shift(1) #Se calcula la suma de los datos Y
  df_1['Xes*Yes']=df_1['X_k+1-X_k']*df_1['Y_k+1+Y_k']
  Coef_Gini=abs(1-((df_1['X_k+1-X_k']*df_1['Y_k+1+Y_k']).sum())) #Se suman los productos de la diferencia de X con las sumas de Y
  print(df_1)
  return Coef_Gini
  

**Datos**

In [ ]:
Variable_X=[0.09,0.33,0.45,0.78,1]
Variable_Y=[0.17,0.48,0.62,0.86,1]


**LLamando a la función y calculando el coef de Gini**

In [ ]:
G=coefGini(Variable_X,Variable_Y)
print("El coeficiente de Gini es:", G)

         VarX  VarY  X_k+1-X_k  Y_k+1+Y_k  Xes*Yes
Clase 1  0.09  0.17        NaN        NaN      NaN
Clase 2  0.33  0.48       0.24       0.65   0.1560
Clase 3  0.45  0.62       0.12       1.10   0.1320
Clase 4  0.78  0.86       0.33       1.48   0.4884
Clase 5  1.00  1.00       0.22       1.86   0.4092
El coeficiente de Gini es: 0.1856


## 2. Algoritmos

1. Dado dos conjuntos de datos ordenados y de tamaños diferentes, realizar una función que mezcle ambos conjunto y genere un nuevo conjunto con todos los datos ordenados.

**Función para unir conjuntos de datos**

In [ ]:
def unir(D1,D2):
  D=D1|D2 #crea la unión de los dos conjuntos
  return D

**Algoritmo burbuja para ordenar**

In [ ]:
def burbuja(D):
  D=list(D) #convierte el conjunto en una lista
  intercambio=True
  while intercambio:
    intercambio=False
    for i in range(len(D)-1):
      if D[i]>D[i+1]:
        D[i], D[i+1]=D[i+1], D[i]
        intercambio=True
  return D #Devuelve el conjunto como una lista ordenada

Aplicar el algoritmo para mezclar y ordenar los siguientes conjuntos:

$$D_1 = \{5, 7, 15, 23, 45, 72, 83\}$$

$$D_2= \{1, 2, 6, 29, 37, 75, 100, 110, 115, 117\}$$

**Datos**

In [ ]:
D1={5,7,15,23,45,72,83}
D2={1,2,6,29,37,75,100,110,115,117}


**Union de conjuntos**

In [ ]:
D=unir(D1,D2) #llama a la función unión de conjuntos
print(D)  #imprime el conjunto unido y sin ordenar


{1, 2, 5, 6, 7, 72, 75, 15, 83, 23, 29, 100, 37, 45, 110, 115, 117}


**Ordenando los elementos del conjunto nuevo**

In [ ]:
print("Datos de la lista ya ordenados")
print(burbuja(D)) #llama a la función de ordenamiento burbuja

Datos de la lista ya ordenados
[1, 2, 5, 6, 7, 15, 23, 29, 37, 45, 72, 75, 83, 100, 110, 115, 117]


2. La equivalencia de los símbolos básicos de los números romanos es la siguiente:

|Número Romano | I | V | X | L | C | D | M |
| --- | --- | --- | --- | --- | --- | --- | --- |
|Número decimal| 1 | 5 | 10 | 50 | 100 | 500 | 1000 |

Los enteros romanos se escriben de acuerdo a las siguientes reglas:

- Si una letra está seguida inmediatamente por una de igual o menor valor, su valor se suma al total acumulado. Así, XX = 20, XV = 15 y VI = 6.
- Si una letra está seguida inmediatamente por una de mayor valor, su valor se sustrae del total acumulado. Así, IV = 4, XL = 40 y CM = 900.

Escriba la función que reciba un string con un número en notación romana, y entregue el entero equivalente:

**Función que convierte en entero el romano**

In [ ]:
def roman_a_decimal(roman):
  romanos={'I':1 , 'V':5, 'X':10, 'L':50, 'C':100, 'D':500, 'M':1000}
  decimal=0

  for i in range(len(roman)):
    if i>0 and romanos[roman[i]]>romanos[roman[i-1]]:
      decimal+=romanos[roman[i]]-2*romanos[roman[i-1]]
    else:
      decimal+=romanos[roman[i]]
  
  return decimal     

**Llamda a la función y escribir el romano**

In [ ]:
str=input("Ingrese el número romano con letra mayúscula")

print(roman_a_decimal(str))


Ingrese el número romano con letra mayúsculaVC
95


## 3. Algoritmos en Series de Tiempo

Una serie de tiempo es una secuencia de valores numéricos obtenidos a intervalos de tiempos regulares.

$$X=\{x_1, x_2,....., x_t, ..., x_T\}$$

1. Las medias móviles con retardo $p$ de una serie de tiempo son las secuencia de todos los promedios de $p$ valores consecutivos de la serie. Realizar una función que retorne el arreglo de las medias móviles con retardo $p$ de la serie.

**Definición de la función para el calculo de medias móviles**

In [ ]:
def media_movil(dato1,p) :
    retardo = np.cumsum(dato1, dtype=float) #crea una lista con los valores de las sumas acumuladas hasta la posición, según la lista original
    retardo[p:] = retardo[p:] - retardo[:-p] 
    return retardo[p - 1:] / p



Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

**Datos**

In [ ]:
Dato1 = [1.5 , 2.89, -0.08, -2.93, -1.35, 2.26, 2.47, -1.05, -2.98, -0.41, 2.78, 1.78, -1.91, -2.71, 0.58, 3. , 0.9 , -2.56, -2.15, 1.5 ]

**LLamando a la función calculo de media movil**

In [ ]:
p=int(input("Ingrese el valor del retardo")) #ingresa el valor del retardo
print(media_movil(Dato1,p)) #imprime la lista de las medias móviles llamando a la función. Se le pasa la lista de datos y el retardo

Ingrese el valor del retardo1
[ 1.5   2.89 -0.08 -2.93 -1.35  2.26  2.47 -1.05 -2.98 -0.41  2.78  1.78
 -1.91 -2.71  0.58  3.    0.9  -2.56 -2.15  1.5 ]


2. Las diferencias finitas de una serie de tiempo son la secuencia de todas las diferencias entre un valor y el anterior. Escribir una función que retorne el arreglo de las diferencias finitas de la serie.

**Función que devuelve arreglo de las diferencias**

In [ ]:
def dif_fin(matriz_2): #recibe la lista
  MaTr={} #se crea un conjunto vacío para cargar la lista
  MaTr['Valor']=matriz_2 #se carga la lista de datos en un conjunto
  df_3=pd.DataFrame(MaTr) #se transforma el conjunto en un dataFrame pandas
  df_3['(Valor+1)-Valor']=(df_3['Valor'].shift(-1)-df_3['Valor']).shift(1) #restamos el un valor y lo restamos con el anterior y se guarda en una columna del DataFrame
  lista_dif=df_3['(Valor+1)-Valor'].tolist() #pasamos la culumna 'Valor+1-Valor' a una lista que es la lista de diferencias
  for i in range(len(lista_dif)):
    lista_dif[i]=round(lista_dif[i],2)
  
  return lista_dif[1:]   #imprimimos desdel el segundo elemento (índice 1), el primero no tiene registro pues el primer elemento no se resta con ninguno anterior




Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

**Datos**

In [ ]:
Dato2 = [ 1.5 , 2.89, -0.08, -2.93, -1.35, 2.26, 2.47, -1.05, -2.98, -0.41, 2.78, 1.78, -1.91, -2.71, 0.58, 3. , 0.9 , -2.56, -2.15, 1.5 ]

**LLamada a la función**

In [ ]:
print(dif_fin(Dato2)) #se llama a al función y se imprime el retorno de la función, que son las diferencias finitas.

[1.39, -2.97, -2.85, 1.58, 3.61, 0.21, -3.52, -1.93, 2.57, 3.19, -1.0, -3.69, -0.8, 3.29, 2.42, -2.1, -3.46, 0.41, 3.65]


3. En algunos métodos se requiere construir la matriz de rezagos de orden p. Esto es, dado la serie de tiempo:

$$X=\{x_1, x_2,....., x_t, ..., x_T\}$$

La matriz de rezagos de orden $p$ está dada por:

$$M = \left[\begin{array}{cccccc}
x_1 & x_2 & ... & x_p\\
x_2 & x_3 & ... & x_{p+1}\\
x_4 & x_5 & ... & x_{p+2}\\
... & ... & ... & ...\\
x_{T-p} & x_{T-p+1} & ... & x_{T-1}\\
x_{T-p+1} & x_{T-p+2} & ... & x_{T}\\
\end{array}
\right]$$ 

Realizar una función que construya dicha estructura de datos.

**Función de para matriz de rezagos**

In [48]:
  def mat_rez(dat,p): #recibe los datos y el orden
    filas=len(dat)-p+1     #se define el número de filas
    columnas=p            #se define el número de columnas
    matriz=[]         #se crea una matriz de vacía
    for i in range(filas): #se recorre el arreglo
      matriz.append([0]*columnas) 
    count=0 #contador para ir trasladando el elemento que va en la primera posición de la fila siguiente
    for i in range(filas):   
      for j in range(columnas):
        matriz[i][j]=dat[j+count]
        if j==(p-1):    #termina con el elemento en la columna y lo compara para trasladar el elemento en la fila siguiente
          count+=1

    z=np.array(matriz) #transforma la matriz a matriz numpy del tipo array
  
    return z.reshape(filas,columnas) #redimensiona el array en filas y columnas para presentarlo de forma rectangular

  

Aplicar la función a los siguientes datos:

Dato = { 1.5 ,  2.89, -0.08, -2.93, -1.35,  2.26,  2.47, -1.05, -2.98,
       -0.41,  2.78,  1.78, -1.91, -2.71,  0.58,  3.  ,  0.9 , -2.56,
       -2.15,  1.5 }

In [49]:
dato4 = [ 1.5 , 2.89, -0.08, -2.93, -1.35, 2.26, 2.47, -1.05, -2.98, -0.41, 2.78, 1.78, -1.91, -2.71, 0.58, 3. , 0.9 , -2.56, -2.15, 1.5 ]

In [50]:
p=int(input("ingrese tamaño orden: "))
print(mat_rez(dato4,p))

ingrese tamaño orden: 4
[[ 1.5   2.89 -0.08 -2.93]
 [ 2.89 -0.08 -2.93 -1.35]
 [-0.08 -2.93 -1.35  2.26]
 [-2.93 -1.35  2.26  2.47]
 [-1.35  2.26  2.47 -1.05]
 [ 2.26  2.47 -1.05 -2.98]
 [ 2.47 -1.05 -2.98 -0.41]
 [-1.05 -2.98 -0.41  2.78]
 [-2.98 -0.41  2.78  1.78]
 [-0.41  2.78  1.78 -1.91]
 [ 2.78  1.78 -1.91 -2.71]
 [ 1.78 -1.91 -2.71  0.58]
 [-1.91 -2.71  0.58  3.  ]
 [-2.71  0.58  3.    0.9 ]
 [ 0.58  3.    0.9  -2.56]
 [ 3.    0.9  -2.56 -2.15]
 [ 0.9  -2.56 -2.15  1.5 ]]
